src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $duree_minutes = null;

    #[ORM\Column]
    private ?bool $est_actif = null;

    #[ORM\ManyToOne(inversedBy: 'services')]
    private ?Categorie $categorie = null;

    /**
     * @var Collection<int, Portfolio>
     */
    #[ORM\OneToMany(targetEntity: Portfolio::class, mappedBy: 'service')]
    private Collection $portfolios;

    public function __construct()
    {
        $this->portfolios = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDureeMinutes(): ?int
    {
        return $this->duree_minutes;
    }

    public function setDureeMinutes(int $duree_minutes): static
    {
        $this->duree_minutes = $duree_minutes;

        return $this;
    }

    public function isEstActif(): ?bool
    {
        return $this->est_actif;
    }

    public function setEstActif(bool $est_actif): static
    {
        $this->est_actif = $est_actif;

        return $this;
    }

    public function getCategorie(): ?categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Portfolio>
     */
    public function getPortfolios(): Collection
    {
        return $this->portfolios;
    }

    public function addPortfolio(Portfolio $portfolio): static
    {
        if (!$this->portfolios->contains($portfolio)) {
            $this->portfolios->add($portfolio);
            $portfolio->setService($this);
        }

        return $this;
    }

    public function removePortfolio(Portfolio $portfolio): static
    {
        if ($this->portfolios->removeElement($portfolio)) {

            if ($portfolio->getService() === $this) {
                $portfolio->setService(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Services.php
<?php

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\CategoriesService;

#[ORM\Entity(repositoryClass: ServicesRepository::class)]
class Services
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $duree_minutes = null;

    #[ORM\Column]
    private ?bool $est_actif = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDureeMinutes(): ?int
    {
        return $this->duree_minutes;
    }

    public function setDureeMinutes(int $duree_minutes): static
    {
        $this->duree_minutes = $duree_minutes;

        return $this;
    }

    public function isEstActif(): ?bool
    {
        return $this->est_actif;
    }

    public function setEstActif(bool $est_actif): static
    {
        $this->est_actif = $est_actif;

        return $this;
    }

    
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Form\Service1Type;
use App\Repository\ServiceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/service')]
final class ServiceController extends AbstractController
{
    #[Route(name: 'app_service_index', methods: ['GET'])]
    public function index(ServiceRepository $serviceRepository): Response
    {
        return $this->render('service/index.html.twig', [
            'services' => $serviceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_service_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $service = new Service();
        $form = $this->createForm(Service1Type::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($service);
            $entityManager->flush();

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('service/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_show', methods: ['GET'])]
    public function show(Service $service): Response
    {
        return $this->render('service/show.html.twig', [
            'service' => $service,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_service_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Service $service, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Service1Type::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('service/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_delete', methods: ['POST'])]
    public function delete(Request $request, Service $service, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($service);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn btn-sm btn-outline-danger">Supprimer</button>
</form>

templates/service/_form.html.twig
{{ form_start(form) }}
    <div class="mb-3">
        {{ form_row(form.nom, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.description, {'attr': {'class': 'form-control', 'rows': 4}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.prix, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.duree_minutes, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.categorie, {'attr': {'class': 'form-select'}}) }}
    </div>
    <div class="d-grid">
        <button class="btn btn-primary btn-lg">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Service{% endblock %}

{% block body %}
    <h1>Modifier les services</h1>

    {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_service_index') }}">back to list</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}

templates/service/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service index{% endblock %}

{% block body %}
    <h1>Service index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Prix</th>
                <th>Duree_minutes</th>
                <th>Est_actif</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for service in services %}
            <tr>
                <td>{{ service.id }}</td>
                <td>{{ service.nom }}</td>
                <td>{{ service.description }}</td>
                <td>{{ service.prix }}</td>
                <td>{{ service.dureeMinutes }}</td>
                <td>{{ service.estActif ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_service_show', {'id': service.id}) }}">show</a>
                    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_service_new') }}">Create new</a>
{% endblock %}

templates/service/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Service{% endblock %}

{% block body %}
    <h1>Create new Service</h1>

    {{ include('service/_form.html.twig') }}

    <a href="{{ path('app_service_index') }}">back to list</a>
{% endblock %}

templates/service/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Service{% endblock %}

{% block body %}
    <h1>Service</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ service.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ service.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ service.description }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ service.prix }}</td>
            </tr>
            <tr>
                <th>Duree_minutes</th>
                <td>{{ service.dureeMinutes }}</td>
            </tr>
            <tr>
                <th>Est_actif</th>
                <td>{{ service.estActif ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_service_index') }}">back to list</a>

    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}