src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $ordre_affichage = null;

    /**
     * @var Collection<int, Service>
     */
    #[ORM\OneToMany(targetEntity: Service::class, mappedBy: 'categorie')]
    private Collection $services;

    public function __construct()
    {
        $this->services = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    public function getOrdreAffichage(): ?int
    {
        return $this->ordre_affichage;
    }

    public function setOrdreAffichage(int $ordre_affichage): static
    {
        $this->ordre_affichage = $ordre_affichage;
        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): static
    {
        if (!$this->services->contains($service)) {
            $this->services->add($service);
            $service->setCategorie($this);
        }

        return $this;
    }

    public function removeService(Service $service): static
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getCategorie() === $this) {
                $service->setCategorie(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $duree_minutes = null;

    #[ORM\Column]
    private ?bool $est_actif = null;

    #[ORM\ManyToOne(inversedBy: 'services')]
    private ?Categorie $categorie = null;

    /**
     * @var Collection<int, Portfolio>
     */
    #[ORM\OneToMany(targetEntity: Portfolio::class, mappedBy: 'service')]
    private Collection $portfolios;

    public function __construct()
    {
        $this->portfolios = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDureeMinutes(): ?int
    {
        return $this->duree_minutes;
    }

    public function setDureeMinutes(int $duree_minutes): static
    {
        $this->duree_minutes = $duree_minutes;

        return $this;
    }

    public function isEstActif(): ?bool
    {
        return $this->est_actif;
    }

    public function setEstActif(bool $est_actif): static
    {
        $this->est_actif = $est_actif;

        return $this;
    }

    public function getCategorie(): ?categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?categorie $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Portfolio>
     */
    public function getPortfolios(): Collection
    {
        return $this->portfolios;
    }

    public function addPortfolio(Portfolio $portfolio): static
    {
        if (!$this->portfolios->contains($portfolio)) {
            $this->portfolios->add($portfolio);
            $portfolio->setService($this);
        }

        return $this;
    }

    public function removePortfolio(Portfolio $portfolio): static
    {
        if ($this->portfolios->removeElement($portfolio)) {

            if ($portfolio->getService() === $this) {
                $portfolio->setService(null);
            }
        }

        return $this;
    }

    
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('ordre_affichage')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/categorie')]
final class CategorieController extends AbstractController
{
    #[Route(name: 'app_categorie_index', methods: ['GET'])]
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_categorie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($categorie);
            $entityManager->flush();

            return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categorie_show', methods: ['GET'])]
    public function show(Categorie $categorie): Response
    {
        return $this->render('categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_categorie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categorie_delete', methods: ['POST'])]
    public function delete(Request $request, Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($categorie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/categorie/_delete_form.html.twig
<form method="post" action="{{ path('app_categorie_delete', {'id': categorie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/categorie/_form.html.twig
{{ form_start(form) }}
    {# Utilise form_row pour chaque champ pour un meilleur contrôle et applique la classe form-control #}
    <div class="mb-3">
        {{ form_row(form.nom, {
            'label': 'Nom de la catégorie :',
            'attr': {'class': 'form-control', 'placeholder': 'Ex: Mains'}
        }) }}
    </div>
    <div class="mb-3">
        {{ form_row(form.ordre_affichage, {
            'label': 'Ordre d\'affichage :',
            'attr': {'class': 'form-control', 'placeholder': 'Ex: 1', 'min': 1},
             'help': 'Un nombre plus petit s\'affiche en premier.'
        }) }}
    </div>


     {# Style du bouton #}
    <div class="d-grid mt-4">
        <button class="btn btn-primary btn-lg">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form) }}

templates/categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Categorie{% endblock %}

{% block body %}
    <h1>Editer une nouvelle catégorie</h1>

    {{ include('categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_categorie_index') }}">Retour à la liste</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestations
{% endblock %}

{% block body %}
	<div class="container my-5">
	    <div class="logo-container">
				<img src="{{ asset('images/Gemini_Generated_Image_iy11sdiy11sdiy11-removebg-preview.png') }}" alt="LineNails Logo" class="hero-logo mb-4"/>
	    </div>
		<div class="d-flex justify-content-between align-items-center mb-4">
			
			{# Apparition du bouton en mode ADMIN #}
			{% if is_granted('ROLE_ADMIN') %}
				<a href="{{ path('app_categorie_new') }}" class="btn btn-primary">
					<i class="bi bi-plus-circle"></i>
					Ajouter une catégorie
				</a>
			{% endif %}
		</div>

		{% for categorie in categories %}
			<h1 class="mb-4 mt-5 text-black services-title">{{ categorie.nom }}</h1>
			<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
				{% for service in categorie.services %}
					<div class="col">
						<div class="card info-card h-100">
							<div class="card-header">{{ service.nom }}</div>
							<div class="card-body">
								{% if service.description %}
									<p class="card-text">{{ service.description }}</p>
								{% endif %}
							</div>
							<div class="card-footer d-flex justify-content-between align-items-center">
								<span class="fw-bold">{{ service.prix|number_format(2, ',', ' ') }}
									€</span>
								<small class="text-white-50">Durée:
									{{ service.dureeMinutes }}
									min</small>
							</div>

							{# --- DÉBUT DE LA SECTION ADMIN --- #}
							{% if is_granted('ROLE_ADMIN') %}
								<div class="card-footer d-flex justify-content-end gap-2">
									<a href="{{ path('app_service_edit', {'id': service.id}) }}" class="btn btn-sm btn-outline-primary">
										<i class="bi bi-pencil"></i>
										Modifier
									</a>
									{# Le formulaire de suppression est généré par make:crud dans templates/service/_delete_form.html.twig #}
									{{ include('service/_delete_form.html.twig', {'service': service}) }}
								</div>
							{% endif %}
							{# --- FIN DE LA SECTION ADMIN --- #}

						</div>
					</div>
				{% else %}
					<div class="col-12">
						<div class="alert alert-info">
							Aucune prestation disponible dans cette catégorie pour le moment.
						</div>
					</div>
				{% endfor %}
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/categorie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Catégorie{% endblock %}

{% block body %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            {# --- On ajoute la structure de la carte ici --- #}
            <div class="card shadow-lg register-card" style="background-color: rgba(0, 0, 0, 0.2); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.2);">
                <div class="card-body p-4 p-md-5">
                    <h1 class="text-center mb-4">Créer une nouvelle catégorie</h1>

                    {# On inclut le formulaire à l'intérieur de la carte #}
                    {{ include('categorie/_form.html.twig') }}

                    {# On ajoute le lien retour en dehors du formulaire mais dans la carte #}
                    <div class="text-center mt-4">
                        <a href="{{ path('app_categorie_index') }}" class="btn btn-outline-secondary">Retour à la liste</a>
                    </div>
                </div>
            </div>
             {# --- Fin de la structure de la carte --- #}
        </div>
    </div>
</div>
{% endblock %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ categorie.nom }}</td>
            </tr>
            <tr>
                <th>Ordre_affichage</th>
                <td>{{ categorie.ordreAffichage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_categorie_index') }}">back to list</a>

    <a href="{{ path('app_categorie_edit', {'id': categorie.id}) }}">edit</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}